### ISSUE TITLE
Build failed on Python 3.6.5 - Gentoo

### ISSUE THREAD

**Issue by archenroot** [emre/storm#166]
Hi,

I am getting error after issuing `$pip install --user storm`:
```
zangetsu@venus /var/lib/layman/archenroot/dev-python/ez_setup $ pip install --user storm
Collecting storm
  Using cached https://files.pythonhosted.org/packages/a7/4c/e5dbc818c432cd80d2e1aa1576f911eda49a3c206c6697db4070f402cda9/storm-0.20.tar.bz2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vddhlj_n/storm/setup.py", line 5, in <module>
        import ez_setup
      File "/tmp/pip-build-vddhlj_n/storm/ez_setup.py", line 106
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vddhlj_n/storm/
```
Is this version supported or should I install older python alongside as well?

Thx.

**Comment by archenroot** [comment]
Mistake, different package I issued storm instead of stormssh -> it works.
