### ISSUE TITLE
installation error on osx yosemite (easy_install)

### ISSUE THREAD

**Issue by aydantasdemir** [emre/storm#89]
full log:

```bash
~ ❯ sudo easy_install stormssh                                                                                                 ⏎
Searching for stormssh
Reading https://pypi.python.org/simple/stormssh/
Best match: stormssh 0.6.5
Downloading https://pypi.python.org/packages/source/s/stormssh/stormssh-0.6.5.tar.gz#md5=38a82b61bd3eb483657b9a7b7204e946
Processing stormssh-0.6.5.tar.gz
Writing /tmp/easy_install-6w7FK9/stormssh-0.6.5/setup.cfg
Running stormssh-0.6.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-6w7FK9/stormssh-0.6.5/egg-dist-tmp-5QEAx6
zip_safe flag not set; analyzing archive contents...
storm.web: module references __file__
Adding stormssh 0.6.5 to easy-install.pth file
Installing storm script to /usr/local/bin

Installed /Library/Python/2.7/site-packages/stormssh-0.6.5-py2.7.egg
Processing dependencies for stormssh
Searching for flask
Reading https://pypi.python.org/simple/flask/
Best match: Flask 0.10.1
Downloading https://pypi.python.org/packages/source/F/Flask/Flask-0.10.1.tar.gz#md5=378670fe456957eb3c27ddaef60b2b24
Processing Flask-0.10.1.tar.gz
Writing /tmp/easy_install-XC5Zl8/Flask-0.10.1/setup.cfg
Running Flask-0.10.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-XC5Zl8/Flask-0.10.1/egg-dist-tmp-_XdZpv
warning: no files found matching '*' under directory 'tests'
warning: no previously-included files matching '*.pyc' found under directory 'docs'
warning: no previously-included files matching '*.pyo' found under directory 'docs'
warning: no previously-included files matching '*.pyc' found under directory 'tests'
warning: no previously-included files matching '*.pyo' found under directory 'tests'
warning: no previously-included files matching '*.pyc' found under directory 'examples'
warning: no previously-included files matching '*.pyo' found under directory 'examples'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'docs/_themes/.git'
Adding Flask 0.10.1 to easy-install.pth file

Installed /Library/Python/2.7/site-packages/Flask-0.10.1-py2.7.egg
Searching for termcolor
Reading https://pypi.python.org/simple/termcolor/
Best match: termcolor 1.1.0
Downloading https://pypi.python.org/packages/source/t/termcolor/termcolor-1.1.0.tar.gz#md5=043e89644f8909d462fbbfa511c768df
Processing termcolor-1.1.0.tar.gz
Writing /tmp/easy_install-nf36UM/termcolor-1.1.0/setup.cfg
Running termcolor-1.1.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-nf36UM/termcolor-1.1.0/egg-dist-tmp-xRtjpY
zip_safe flag not set; analyzing archive contents...
Adding termcolor 1.1.0 to easy-install.pth file

Installed /Library/Python/2.7/site-packages/termcolor-1.1.0-py2.7.egg
Searching for paramiko
Reading https://pypi.python.org/simple/paramiko/
Best match: paramiko 1.15.1
Downloading https://pypi.python.org/packages/source/p/paramiko/paramiko-1.15.1.tar.gz#md5=48c274c3f9b1282932567b21f6acf3b5
Processing paramiko-1.15.1.tar.gz
Writing /tmp/easy_install-91t7VN/paramiko-1.15.1/setup.cfg
Running paramiko-1.15.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-91t7VN/paramiko-1.15.1/egg-dist-tmp-SZPghq
zip_safe flag not set; analyzing archive contents...
Adding paramiko 1.15.1 to easy-install.pth file

Installed /Library/Python/2.7/site-packages/paramiko-1.15.1-py2.7.egg
Searching for itsdangerous>=0.21
Reading https://pypi.python.org/simple/itsdangerous/
Best match: itsdangerous 0.24
Downloading https://pypi.python.org/packages/source/i/itsdangerous/itsdangerous-0.24.tar.gz#md5=a3d55aa79369aef5345c036a8a26307f
Processing itsdangerous-0.24.tar.gz
Writing /tmp/easy_install-Uvqc3C/itsdangerous-0.24/setup.cfg
Running itsdangerous-0.24/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Uvqc3C/itsdangerous-0.24/egg-dist-tmp-vIDI6Q
warning: no previously-included files matching '*' found under directory 'docs/_build'
Adding itsdangerous 0.24 to easy-install.pth file

Installed /Library/Python/2.7/site-packages/itsdangerous-0.24-py2.7.egg
Searching for Jinja2>=2.4
Reading https://pypi.python.org/simple/Jinja2/
Best match: Jinja2 2.7.3
Downloading https://pypi.python.org/packages/source/J/Jinja2/Jinja2-2.7.3.tar.gz#md5=b9dffd2f3b43d673802fe857c8445b1a
Processing Jinja2-2.7.3.tar.gz
Writing /tmp/easy_install-V2mWvj/Jinja2-2.7.3/setup.cfg
Running Jinja2-2.7.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-V2mWvj/Jinja2-2.7.3/egg-dist-tmp-SISMG0
warning: no files found matching '*' under directory 'custom_fixers'
warning: no previously-included files matching '*' found under directory 'docs/_build'
warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
warning: no previously-included files matching '*.pyc' found under directory 'docs'
warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
warning: no previously-included files matching '*.pyo' found under directory 'docs'
Adding Jinja2 2.7.3 to easy-install.pth file

Installed /Library/Python/2.7/site-packages/Jinja2-2.7.3-py2.7.egg
Searching for Werkzeug>=0.7
Reading https://pypi.python.org/simple/Werkzeug/
Best match: Werkzeug 0.9.6
Downloading https://pypi.python.org/packages/source/W/Werkzeug/Werkzeug-0.9.6.tar.gz#md5=f7afcadc03b0f2267bdc156c34586043


Processing Werkzeug-0.9.6.tar.gz
Writing /tmp/easy_install-6KDzpg/Werkzeug-0.9.6/setup.cfg
Running Werkzeug-0.9.6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-6KDzpg/Werkzeug-0.9.6/egg-dist-tmp-YUjIyQ
warning: no files found matching '*' under directory 'werkzeug/debug/templates'
warning: no files found matching '*' under directory 'tests'
warning: no previously-included files matching '*.pyc' found under directory 'docs'
warning: no previously-included files matching '*.pyo' found under directory 'docs'
warning: no previously-included files matching '*.pyc' found under directory 'tests'
warning: no previously-included files matching '*.pyo' found under directory 'tests'
warning: no previously-included files matching '*.pyc' found under directory 'examples'
warning: no previously-included files matching '*.pyo' found under directory 'examples'
no previously-included directories found matching 'docs/_build'
Adding Werkzeug 0.9.6 to easy-install.pth file

Installed /Library/Python/2.7/site-packages/Werkzeug-0.9.6-py2.7.egg
Searching for ecdsa>=0.11
Reading https://pypi.python.org/simple/ecdsa/
Best match: ecdsa 0.11
Downloading https://pypi.python.org/packages/source/e/ecdsa/ecdsa-0.11.tar.gz#md5=8ef586fe4dbb156697d756900cb41d7c
Processing ecdsa-0.11.tar.gz
Writing /tmp/easy_install-1FQ3XS/ecdsa-0.11/setup.cfg
Running ecdsa-0.11/setup.py -q bdist_egg --dist-dir /tmp/easy_install-1FQ3XS/ecdsa-0.11/egg-dist-tmp-WbKN4C
zip_safe flag not set; analyzing archive contents...
Adding ecdsa 0.11 to easy-install.pth file

Installed /Library/Python/2.7/site-packages/ecdsa-0.11-py2.7.egg
Searching for pycrypto>=2.1,!=2.4
Reading https://pypi.python.org/simple/pycrypto/
Best match: pycrypto 2.6.1
Downloading https://pypi.python.org/packages/source/p/pycrypto/pycrypto-2.6.1.tar.gz#md5=55a61a054aa66812daf5161a0d5d7eda
Processing pycrypto-2.6.1.tar.gz
Writing /tmp/easy_install-oJ3s2g/pycrypto-2.6.1/setup.cfg
Running pycrypto-2.6.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-oJ3s2g/pycrypto-2.6.1/egg-dist-tmp-CWckwa
configure: error: in `/private/tmp/easy_install-oJ3s2g/pycrypto-2.6.1':
configure: error: C compiler cannot create executables
See `config.log' for more details
Traceback (most recent call last):
  File "/usr/bin/easy_install-2.7", line 11, in <module>
    load_entry_point('setuptools==1.1.6', 'console_scripts', 'easy_install')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1925, in main
    with_ei_usage(lambda:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1912, in with_ei_usage
    return f()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1929, in <lambda>
    distclass=DistributionWithoutHelpCommands, **kw
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 374, in run
    self.easy_install(spec, not self.no_deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 609, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 641, in install_item
    self.process_distribution(spec, dist, deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 687, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 568, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 806, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 818, in obtain
    return installer(requirement)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 609, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 639, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 825, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1031, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1016, in run_setup
    run_setup(setup_script, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 69, in run_setup
    lambda: execfile(
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 120, in run
    return func()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 71, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 456, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/bdist_egg.py", line 185, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/bdist_egg.py", line 171, in call_command
    self.run_command(cmdname)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/install_lib.py", line 20, in run
    self.build()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 251, in run
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 278, in run
RuntimeError: autoconf error
```

**Comment by simonweil** [comment]
Install with `brew install stormssh`, it works perfectly.

**Comment by emre** [comment]
thanks @simonweil.
